username = input(" Имя пользователя ")
title = input(" Заголовок заметки ")
content = input(" Описание заметки ")
status = input(" Статус заметки ")
created_date = input(" ДД-ММ-ГГГГ ")
print(created_date[:-5])
issue_date = input(" ДД-ММ-ГГГГ ")
print(issue_date[:-5])