username = input(" Имя пользователя: ")
title = input(" Заголовок заметки: ")
text = ["1. Основные темы","2. Персонажи","3. Рекомендаций для чтения"]
print(input(text[0]))
print(input(text[1]))
print(input(text[2]))
content = input(" Описание заметки: ")
status = input(" Статус заметки: ")
created_date = input(" ДД-ММ-ГГГГ: ")
print(created_date[:-5])
issue_date = input(" ДД-ММ-ГГГГ ")
print(issue_date[:-5])
#text = (input( ' 1 . Основные темы:' '\n 2 . Персонажи:'   '\n 3 . Рекомендаций для чтения: ' ))
#text = input( '1.Основные темы:')
#text1 = input('2.Персонажи:')
#text2 = input('3.Рекомендаций для чтения:')