username = input(" Имя пользователя: ")
title = input(" Заголовок заметки: ")
text = ( ' 1 . Основные темы\n 2 . Персонажи \n 3 . Рекомендаций для чтения ' )
print(input(text))
content = input(" Описание заметки: ")
status = input(" Статус заметки: ")
created_date = input(" ДД-ММ-ГГГГ: ")
print(created_date[:-5])
issue_date = input(" ДД-ММ-ГГГГ ")
print(issue_date[:-5])