print("username:", 'Имя пользователя')
print("title:", 'Заголовок заметки')
print("content:", 'описание заметки')
print("status:", 'Статус заметки')
print("created_date:", '17-11-2025')
print("issue_date:", '17-11-2025')
